Repository Dulce-Work-Schedule/2018.1-Dulce_Profile, pull requests merged in 2018-06, with the labels that each got.

#50 HOTFIX corrigindo deploy.sh e excluindo docker-compose desnecessário.
  Client/start-user.yml
  utils/deploy.sh
Labels: 0-DevOps, 1-Infraestrutura, 2-Deploy Contínuo, 4-Adicionado, 5-Iniciante

#58 Fix #55, Fix #44, Fix #54 Criando Profile, Fazendo validações e Fazen…
  Client/api.js
  Client/client_user.js
  Server/_user.js
  Server/test/user.test.js
  Server/user.js
Labels: 0-Developers, 1-Produto, 2-Feature, 4-Planejado, 5-Intermediário

#60 Fix #45 Listando profiles
  Client/api.js
  Server/_user.js
  Server/test/user.test.js
Labels: 0-Developers, 1-Produto, 2-Feature, 4-Planejado, 5-Intermediário

#62 Fix #61 finalizando rota de procurar perfil
  Client/api.js
  Server/_user.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-Task, 4-Adicionado, 5-Intermediário
